### ISSUE TITLE
R 4.0.3 compatibility

### ISSUE THREAD

**Issue by tai-mi** [amcdavid/CellaRepertorium#8]
Hello,

I am trying to install the package on R 4.0.3 and am getting the error message "package ‘CellaRepertorium’ is not available for this version of R"
Is this another issue on my end or is it not compatible?

**Comment by amcdavid** [comment]
It's definitely compatible. Did you install with `BiocManager::install`? `install.packages` won't work.

**Comment by tai-mi** [comment]
Yeah I used BiocManager and got an output of (after updating packages): 

```
The downloaded source packages are in
	‘C:\Users\spamt\AppData\Local\Temp\RtmpQTx8LI\downloaded_packages’
Warning message:
package ‘CellaRepertorium’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

**Comment by amcdavid** [comment]
Can you provide full input and output? It's impossible to debug someone's system without knowing exactly what they typed and what the output was.

 I suspect this may be a transient issue with a binary package (that CellaRepertorium depends on) not being available for windows on cran.  If you have Rtools installed (can compile R packages source) you could try 

    BiocManager::install('CellaRepertorium', type = 'source')

**Comment by tai-mi** [comment]
The full output (with Rtools installed) was 


```
> BiocManager::install('CellaRepertorium', type = 'source')
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.3
  (2020-10-10)
Installing package(s) 'CellaRepertorium'
Installation path not writeable, unable to update packages: boot,
  class, codetools, foreign, KernSmooth, Matrix, nlme, nnet,
  spatial
Warning message:
package ‘CellaRepertorium’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```
Even after having successfully updated the listed packages from source with no errors

**Comment by amcdavid** [comment]
I believe this is because the package has dependencies that require upgraded versions of the "unable to update" packages listed in the error message.   Though the error message R gives is certainly not very transparent about this.   If you don't want to upgrade them system-wide you could use the renv package, or set R_LIBS_USER (or maybe R_LIBS_SITE) on a per-project basis.  See `?.libPaths()` and the R administration guide https://cran.r-project.org/doc/manuals/r-release/R-admin.html

**Comment by tai-mi** [comment]
Thanks for your help, it works now! The issue was just that I was using BioConductor 3.11 instead of 3.12

**Comment by amcdavid** [comment]
Yup, that would do it, too.  The error really could be more informative.  I'll add a comment about checking `BiocManager::valid()` to the install instructions to hopefully save others some headache.
